### ISSUE TITLE
Crash on start up if .env doesn't exist

### ISSUE THREAD

**Issue by TheCallSign** [panmnesia/panmnesia-server#4]
Panmnesia server crashes if the `.env` file does not exist when starting the server. A temporary work around is to create the file to be populated automatically when the server starts.

The error thrown: 
```
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Documents\code\node\panmnesia-server\.env'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at SettingsController.refresh (C:\Users\Administrator\Documents\code\node\panmnesia-server\src\SettingsController.js:62:25)
    at new SettingsController (C:\Users\Administrator\Documents\code\node\panmnesia-server\src\SettingsController.js:51:10)
```

**Comment by TheCallSign** [comment]
Fixed in PR #5
